version: '3.7'

services:

  truck-db:
    container_name: truck-db
    image: registry.gitlab.com/mofoyoda/docker-debian-gisdb/debian-gisdb:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../data:/data
      - ../data/pgdata:/var/lib/postgresql/data/pgdata
      - ./postgresql:/pg_config
    ports:
      - 45432:5432
    networks:
      - truck

  truck-osm:
    container_name: truck-osm
    image: registry.gitlab.com/urbica/dt/mcm/docker-alpine-osm:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../data/osm:/data
      - ../scripts/osm:/scripts
      - ../configs/osm2pgsql:/configs/osm2pgsql
      - ./cron:/etc/cron.d
      - ../scripts/osm/docker-entry.sh:/docker-entry.sh
      - ../scripts/osm/docker-cmd.sh:/docker-cmd.sh
    networks:
      - truck

  truck-osmosis:
    container_name: truck-osmosis
    image:   yagajs/osmosis:latest
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../data/osm:/data
    networks:
      - truck

  truck-martin:
    container_name: truck-martin
    image: urbica/martin
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      - truck

  truck-api:
    container_name: truck-api
    image: postgrest/postgrest:latest
    restart: always
    env_file:
      - ../.env
    networks:
      - truck
    ports:
      - 45003:3000
    depends_on:
      - truck-db

networks:
  truck:
    external: true
  proxy:
    external: true
